import os
import json
import nltk
from pathlib import Path
from loguru import logger
from rank_bm25 import BM25Okapi
from dotenv import load_dotenv

load_dotenv()

BM25_CAPTIONS_FILE = os.getenv("BM25_CAPTIONS_FILE", "./data/captions/captions.json")

# download all required NLTK data silently on first run
for resource in ["punkt", "punkt_tab", "stopwords"]:
    try:
        nltk.data.find(f"tokenizers/{resource}")
    except LookupError:
        nltk.download(resource, quiet=True)

def _tokenise(text: str) -> list[str]:
    return nltk.word_tokenize(text.lower())


class BM25Index:
    """
    Sparse keyword index over image captions — the sparse leg.

    Captions are short text descriptions generated by moondream at index time.
    They exist purely so BM25 has text to keyword-match against.
    They are NEVER used to create embedding vectors.

    captions.json format:
    {
        "img_001": "three red cars parked near a grey building",
        "img_002": "two people playing football on a grass field"
    }
    """

    def __init__(self):
        self.image_ids: list[str]        = []
        self.captions:  dict[str, str]   = {}
        self.bm25:      BM25Okapi | None = None
        self._path = Path(BM25_CAPTIONS_FILE)

        if self._path.exists():
            self._load()
        else:
            logger.warning(
                f"No captions file at {BM25_CAPTIONS_FILE}. "
                "Run Indexer.index_directory() to build."
            )

    # ── Build ────────────────────────────────────────────────

    def build(self, captions: dict[str, str]) -> None:
        """Build BM25 index from {image_id: caption} dict and save to disk."""
        self._save(captions)
        self._build_index(captions)
        logger.info(f"BM25 index built — {len(captions)} captions indexed")

    def _build_index(self, captions: dict[str, str]) -> None:
        self.captions  = captions
        self.image_ids = list(captions.keys())
        self.bm25      = BM25Okapi([_tokenise(c) for c in captions.values()])

    def _load(self) -> None:
        with open(self._path) as f:
            captions = json.load(f)
        self._build_index(captions)
        logger.info(f"BM25 loaded from disk — {len(self.image_ids)} captions")

    def _save(self, captions: dict[str, str]) -> None:
        self._path.parent.mkdir(parents=True, exist_ok=True)
        with open(self._path, "w") as f:
            json.dump(captions, f, indent=2)
        logger.info(f"Captions saved to {self._path}")

    # ── Query ────────────────────────────────────────────────

    def query(self, text: str, top_n: int = 20) -> list[dict]:
        """
        Keyword search over captions.

        Returns:
            [{"image_id", "score", "rank"}, ...]
            Only results with score > 0 are returned.
        """
        if self.bm25 is None:
            logger.error("BM25 index not built. Run indexing first.")
            return []

        scores = self.bm25.get_scores(_tokenise(text))
        ranked = sorted(zip(self.image_ids, scores), key=lambda x: x[1], reverse=True)

        results = []
        rank = 1
        for image_id, score in ranked:
            if score <= 0:
                continue
            results.append({
                "image_id": image_id,
                "score":    round(float(score), 4),
                "rank":     rank,
            })
            rank += 1
            if rank > top_n:
                break

        logger.debug(f"BM25 '{text[:50]}' → {len(results)} results")
        return results

    def get_caption(self, image_id: str) -> str:
        return self.captions.get(image_id, "")

    def is_ready(self) -> bool:
        return self.bm25 is not None

    def count(self) -> int:
        return len(self.image_ids)