import os
from loguru import logger
from dotenv import load_dotenv

load_dotenv()

RERANKER_MODEL_ID = os.getenv("RERANKER_MODEL_ID", "BAAI/bge-reranker-base")
RERANKER_DEVICE   = os.getenv("RERANKER_DEVICE",   "cpu")
RERANKER_TOP_K    = int(os.getenv("RERANKER_TOP_K", 4))


class Reranker:
    """
    Cross-encoder re-ranking — the final quality gate.

    WHY RERANK:
    Dense and sparse retrieval both use bi-encoders — they embed
    the query and each candidate independently, then compare.
    This is fast but misses fine-grained query-candidate interactions.

    A cross-encoder sees the query AND candidate TOGETHER, scoring
    their joint relevance. This is much more accurate but too slow
    to run on the full index — so we run it only on the top candidates
    from RRF fusion (typically 20-40 items).

    MODEL:
    BGE-reranker-base from BAAI. Free, MIT license, runs on CPU.
    Takes (query, caption) pairs and outputs a relevance score.

    NOTE:
    The reranker scores captions, not raw images — because it needs text.
    This is fine: captions are accurate descriptions of the images
    generated by moondream, so reranking on captions effectively
    reranks the images themselves.
    """

    def __init__(self):
        from FlagEmbedding import FlagReranker
        logger.info(f"Loading reranker: {RERANKER_MODEL_ID}")
        self.reranker = FlagReranker(
            RERANKER_MODEL_ID,
            use_fp16=False,   # fp16 not supported on CPU Mac
            device=RERANKER_DEVICE,
        )
        logger.info("Reranker loaded")

    def rerank(
        self,
        question:   str,
        candidates: list[dict],
        bm25_index,
        top_k:      int | None = None,
    ) -> list[dict]:
        """
        Re-rank RRF candidates using cross-encoder scoring.

        Args:
            question:   the user's VQA question
            candidates: output of rrf_fusion() — list of dicts with image_id
            bm25_index: BM25Index instance — used to look up captions per image
            top_k:      number of final results to return (default RERANKER_TOP_K)

        Returns:
            Top k candidates sorted by reranker score descending.
            Each item includes all RRF fields plus:
            {
                "reranker_score": 3.84,
                "final_rank":     1,
            }
        """
        top_k = top_k or RERANKER_TOP_K

        if not candidates:
            logger.warning("Reranker received empty candidate list")
            return []

        # build (question, caption) pairs for cross-encoder
        pairs    = []
        valid    = []

        for c in candidates:
            caption = bm25_index.get_caption(c["image_id"])
            if not caption:
                # if no caption exists use image_id as fallback text
                caption = c["image_id"].replace("_", " ")
            pairs.append([question, caption])
            valid.append(c)

        logger.debug(f"Reranking {len(pairs)} candidates for: '{question[:60]}'")

        scores = self.reranker.compute_score(pairs, normalize=True)

        # handle single-item case where compute_score returns a float
        if isinstance(scores, float):
            scores = [scores]

        # attach scores and sort
        for candidate, score in zip(valid, scores):
            candidate["reranker_score"] = round(float(score), 4)

        reranked = sorted(valid, key=lambda x: x["reranker_score"], reverse=True)

        # add final rank and trim to top_k
        for i, item in enumerate(reranked[:top_k], start=1):
            item["final_rank"] = i

        result = reranked[:top_k]

        logger.info(
            f"Reranker: {len(candidates)} candidates → top {len(result)} selected"
        )
        return result